name: Qbtools qbmos
url: "https://github.com/wk275/qbtools-v3_HA-addons/tree/main/qbmos"
description: Qbtools qbmos mqtt server starts default on port 51883
version: 3.0
image: wk275/qbmos
slug: qbmos
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  MQTT_USER: 
  MQTT_PASSWORD:
schema:
  MQTT_USER: str?
  MQTT_PASSWORD: str?
services:
  - qbmos:provide
legacy: true
ports:
  "1883/tcp": 51883