name: Qbtools mqtt server
description: Qbtools mosquitto mqtt server
version: 3.0
image: wk275/qbmos
slug: qbmos
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PASSWORD: str?
