name: wk275/qbmos
url: "https://github.com/wk275/qbtools-v3_HA-addons/tree/main/qbmos"
description: "Qbtools mqtt server. Please enter your specific user and password in the configuration tab."
version: latest
image: wk275/qbmos
slug: qbmos
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  MQTT_USER: 
  MQTT_PASSWORD:
schema:
  MQTT_USER: str?
  MQTT_PASSWORD: str?
ports:
  "1883/tcp": 51883
legacy: true