name: Qbus MQTT Gateway
description: Interface bewteen QBus controller and MQTT server
version: 3.1.1.2
image: wk275/qbusmqtt
slug: qbusmqtt
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PASSWORD: str?
  
legacy: true