name: wk275/qbusmqtt
url: "https://github.com/wk275/qbtools-v3_HA-addons/tree/main/qbusmqtt"
description: "Qbtools qbusmqtt gateway. Please enter your specific user and password in the configuration tab. Check the qbmos hostname!"
version: latest
image: wk275/qbusmqtt
slug: qbusmqtt
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  MQTT_HOST: "9d6db495-qbmos"
  MQTT_PORT: "1883"
  MQTT_USER: 
  MQTT_PASSWORD: 
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PASSWORD: str?
legacy: true