name: Qbtools qbusmqtt
url: "https://github.com/wk275/qbtools-v3_HA-addons/tree/main/qbusmqtt"
description: Qbtools qbusmqtt server connects to qbmos server on default port 51883
version: 3.1.1.2
image: wk275/qbusmqtt
slug: qbusmqtt
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  MQTT_HOST: "0.0.0.0"
  MQTT_PORT: "51883"
  MQTT_USER: 
  MQTT_PASSWORD: 
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PASSWORD: str?
services:
  - 'qbusmqtt:provide'
  - 'qbmos:need'
legacy: true