name: Qbus MQTT Gateway
url: "https://github.com/wk275/qbtools-v3_HA-addons/tree/main/qbusmqtt"
description: Interface between QBus controller and MQTT server
version: 3.1.1.2
image: wk275/qbusmqtt
slug: qbusmqtt
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  MQTT_HOST: "0.0.0.0"
  MQTT_PORT: "51883"
  MQTT_USER: "appmos"
  MQTT_PASSWORD: "ncekoznczoZDIZOSJCé38901"
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PASSWORD: str?
legacy: true