name: wk275/qbtools
url: "https://github.com/wk275/qbtools-v3_HA-addons/tree/main/qbtools"
description: "Qbtools HA server. Please enter your specific user and password in the configuration tab. Check the qbmos hostname!"
version: 3.1.2
image: wk275/qbtools
slug: qbtools
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
ports:
  "1880/tcp": 51881
ports_description:
  "1880/tcp": "51881/tcp => HTTP port for qbusGet & qbusSet"
options:
  MQTT_HOST: "9d6db495-qbmos"
  MQTT_PORT: "1883"
  MQTT_USER: 
  MQTT_PASSWORD: 
  INFLUXDB2_URL: "e.g. http://<influxdbV2 ip address>:<influxdbV2 port>"
  INFLUXDB2_ORG: 
  INFLUXDB2_BUCKET:
  INFLUXDB2_TOKEN: 
schema:
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USER: str?
  MQTT_PASSWORD: str?
  INFLUXDB2_URL: str
  INFLUXDB2_ORG: str 
  INFLUXDB2_BUCKET: str
  INFLUXDB2_TOKEN: str
map:
  - type: addon_config
    read_only: False
    path: /HA_parms
legacy: true
